name: sdit_piket_app
description: "Aplikasi Android Guru Piket SDIT Ukhuwah"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^5.1.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.0
  firebase_database: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1 # GENERATOR ICON HP

# KONFIGURASI ICON DI LAYAR UTAMA HP ANDROID
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#0F172A"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

# DAFTAR ASSETS DALAM APLIKASI
flutter:
  uses-material-design: true
  assets:
    - images/logo_sekolah.png
