name: sdit_piket_app
description: "Aplikasi Android Guru Piket SDIT Ukhuwah"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  mobile_scanner: ^5.1.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  # PACKAGE FIREBASE REALTIME DATABASE
  firebase_core: ^2.27.0
  firebase_database: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
